In [1]:
# from prettytable import PrettyTable
# from prettytable import DEFAULT
# PrettyTable.set_style(DEFAULT)

In [2]:
# insert records into the database 
import pandas as pd
import sqlite3 as sql
import os
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [3]:
cnn=sql.connect('airlines.db')

In [4]:
%load_ext sql

In [5]:
%sql sqlite:///airlines.db

In [6]:
%%sql
insert into aircrafts VALUES ('AC060', 350, 'Boeing', '2024-01-01');
insert into aircrafts VALUES ('AC061', 350, 'Boeing', '2024-01-01');

 * sqlite:///airlines.db
1 rows affected.
1 rows affected.

[]

In [7]:
%%sql
select * from aircrafts Order by AcNumber Desc Limit 5;

 * sqlite:///airlines.db
Done.

[('AC061', 350, 'Boeing', '2024-01-01'),
 ('AC061', 350, 'Boeing', '2024-01-01'),
 ('AC060', 350, 'Boeing', '2024-01-01'),
 ('AC060', 350, 'Boeing', '2024-01-01'),
 ('AC050', 250, 'Boeing', '2018-10-30')]

In [8]:
%%sql
SELECT name FROM sqlite_master WHERE type='trigger';

 * sqlite:///airlines.db
Done.

[('InsertAircraftLog',),
 ('InsertScheduleLog',),
 ('InsertPassengerLog',),
 ('updatePassengerLog',),
 ('deletePassengerLog',),
 ('insertTransactionLog',),
 ('updateTransactionLog',)]

In [9]:
%%sql
select * from logs;

 * sqlite:///airlines.db
Done.

[(1, 'INSERT', '2024-12-04 20:02:03', 'Aircraft: AC060, 350, Boeing, 2024-01-01'),
 (2, 'INSERT', '2024-12-04 20:02:03', 'Aircraft: AC061, 350, Boeing, 2024-01-01'),
 (3, 'INSERT', '2024-12-04 20:04:17', 'Flight_Schedule: 22, 2024-12-09 14:04:00, 2024-12-09 14:04:00, 2024-12-09 14:04:00, AC005, 2'),
 (4, 'UPDATE', '2024-12-04 20:16:25', 'Booking: Old: 10, 2024-04-23 00:00:00, 2024-10-19 00:00:00, 78, 36, 1, 38, 32, 47 | New: 10, 2024-04-23 00:00:00, 2024-10-19 00:00:00, 78, 36, 1, 38, 32, 48'),
 (5, 'UPDATE', '2024-12-04 20:16:34', 'Booking: Old: 10, 2024-04-23 00:00:00, 2024-10-19 00:00:00, 78, 36, 1, 38, 32, 48 | New: 10, 2024-04-23 00:00:00, 2024-10-19 00:00:00, 78, 36, 1, 38, 44, 48'),
 (6, 'INSERT', '2024-12-07 00:10:27', 'Aircraft: AC060, 350, Boeing, 2024-01-01'),
 (7, 'INSERT', '2024-12-07 00:10:27', 'Aircraft: AC061, 350, Boeing, 2024-01-01')]

In [10]:
%%sql 
SELECT name FROM sqlite_master WHERE type='table'

 * sqlite:///airlines.db
Done.

[('sqlite_sequence',),
 ('Aircrafts',),
 ('AirFare',),
 ('Branches',),
 ('Charges',),
 ('Contact_Details',),
 ('Countries',),
 ('Discounts',),
 ('Employee',),
 ('Flight_Schedule',),
 ('Passengers',),
 ('Route',),
 ('State',),
 ('Transactions',),
 ('LOGS',)]

In [11]:
path=os.path.abspath(os.path.join(os.getcwd(),".."))
path=os.path.join(path,'data')
path

'd:\\pythonProjects\\airlines_management\\data'

In [12]:
%%sql
select * from Aircrafts;

 * sqlite:///airlines.db
Done.

[('AC001', 150, 'Boeing', '2009-03-01'),
 ('AC002', 200, 'Boeing', '2005-05-16'),
 ('AC003', 150, 'Boeing', '2001-03-03'),
 ('AC004', 150, 'Embraer', '2001-02-25'),
 ('AC005', 300, 'Embraer', '2011-05-07'),
 ('AC006', 300, 'Embraer', '2003-09-01'),
 ('AC007', 150, 'Boeing', '2001-12-23'),
 ('AC008', 300, 'Airbus', '2006-02-11'),
 ('AC009', 250, 'Embraer', '2017-10-11'),
 ('AC010', 150, 'Airbus', '2010-03-23'),
 ('AC011', 150, 'Embraer', '2007-01-08'),
 ('AC012', 200, 'Embraer', '2014-09-04'),
 ('AC013', 200, 'Embraer', '2000-12-25'),
 ('AC014', 200, 'Embraer', '2000-04-02'),
 ('AC015', 300, 'Airbus', '2002-10-31'),
 ('AC016', 200, 'Airbus', '2005-06-14'),
 ('AC017', 250, 'Embraer', '2019-05-22'),
 ('AC018', 150, 'Airbus', '2007-09-27'),
 ('AC019', 250, 'Embraer', '2018-07-04'),
 ('AC020', 200, 'Boeing', '2005-10-13'),
 ('AC021', 200, 'Airbus', '2019-09-13'),
 ('AC022', 250, 'Airbus', '2003-01-23'),
 ('AC023', 150, 'Boeing', '2002-05-02'),
 ('AC024', 200, 'Airbus', '2015-08-17'),
 ('AC025', 150, 'Airbus', '2016-07-13'),
 ('AC026', 250, 'Embraer', '2016-12-09'),
 ('AC027', 150, 'Embraer', '2014-06-02'),
 ('AC028', 200, 'Airbus', '2003-10-08'),
 ('AC029', 150, 'Embraer', '2006-10-21'),
 ('AC030', 300, 'Airbus', '2019-09-07'),
 ('AC031', 150, 'Airbus', '2001-10-10'),
 ('AC032', 300, 'Airbus', '2006-09-27'),
 ('AC033', 250, 'Airbus', '2003-05-24'),
 ('AC034', 300, 'Boeing', '2007-12-06'),
 ('AC035', 250, 'Boeing', '2009-02-11'),
 ('AC036', 200, 'Airbus', '2015-04-20'),
 ('AC037', 150, 'Embraer', '2010-05-12'),
 ('AC038', 300, 'Boeing', '2001-02-16'),
 ('AC039', 300, 'Boeing', '2010-04-22'),
 ('AC040', 300, 'Airbus', '2008-11-05'),
 ('AC041', 300, 'Airbus', '2002-01-10'),
 ('AC042', 250, 'Airbus', '2012-03-26'),
 ('AC043', 150, 'Boeing', '2011-08-23'),
 ('AC044', 250, 'Boeing', '2013-05-30'),
 ('AC045', 150, 'Embraer', '2016-06-20'),
 ('AC046', 200, 'Airbus', '2017-07-04'),
 ('AC047', 150, 'Airbus', '2008-04-15'),
 ('AC048', 200, 'Airbus', '2010-07-31'),
 ('AC049', 150, 'Boeing', '2018-10-05'),
 ('AC050', 250, 'Boeing', '2018-10-30'),
 ('AC060', 350, 'Boeing', '2024-01-01'),
 ('AC061', 350, 'Boeing', '2024-01-01'),
 ('AC060', 350, 'Boeing', '2024-01-01'),
 ('AC061', 350, 'Boeing', '2024-01-01')]

%%sql
delete from Aircrafts where AcNumber='AC051';

In [13]:
%%sql
SELECT FlID,FlightDate,Departure,Arrival,Aircraft, Airport, Destination FROM Flight_Schedule f inner join AirFare a on f.NetFare=a.AfID inner join Route r on a.Route=r.RtID

 * sqlite:///airlines.db
Done.

[(1, '2025-05-27 18:00:00', '2025-05-27 18:00:00', '2025-05-27 23:00:00', 'AC001', 'JFK International', 'Singapore Changi'),
 (2, '2025-07-06 08:00:00', '2025-07-06 08:00:00', '2025-07-06 17:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (3, '2025-05-02 10:00:00', '2025-05-02 10:00:00', '2025-05-02 16:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (4, '2024-11-19 21:00:00', '2024-11-19 21:00:00', '2024-11-20 04:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (5, '2025-08-21 19:00:00', '2025-08-21 19:00:00', '2025-08-22 02:00:00', 'AC001', 'Dallas/Fort Worth International', 'Toronto Pearson'),
 (6, '2024-04-08 23:00:00', '2024-04-08 23:00:00', '2024-04-09 04:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (7, '2025-06-04 08:00:00', '2025-06-04 08:00:00', '2025-06-04 17:00:00', 'AC001', 'Orlando International', 'Paris Charles de Gaulle'),
 (8, '2025-09-20 12:00:00', '2025-09-20 12:00:00', '2025-09-20 19:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (9, '2024-02-08 23:00:00', '2024-02-08 23:00:00', '2024-02-09 02:00:00', 'AC001', 'Orlando International', 'Paris Charles de Gaulle'),
 (10, '2024-02-26 02:00:00', '2024-02-26 02:00:00', '2024-02-26 10:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (11, '2025-07-22 04:00:00', '2025-07-22 04:00:00', '2025-07-22 07:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (12, '2024-02-01 17:00:00', '2024-02-01 17:00:00', '2024-02-01 23:00:00', 'AC006', 'Denver International', 'Dubai International'),
 (13, '2025-05-12 09:00:00', '2025-05-12 09:00:00', '2025-05-12 17:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (14, '2025-01-11 03:00:00', '2025-01-11 03:00:00', '2025-01-11 10:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (15, '2024-02-07 10:00:00', '2024-02-07 10:00:00', '2024-02-07 15:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (16, '2025-10-05 23:00:00', '2025-10-05 23:00:00', '2025-10-06 09:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (17, '2025-04-03 05:00:00', '2025-04-03 05:00:00', '2025-04-03 11:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (18, '2024-10-01 04:00:00', '2024-10-01 04:00:00', '2024-10-01 06:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (19, '2024-04-24 23:00:00', '2024-04-24 23:00:00', '2024-04-25 01:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (20, '2025-06-06 19:00:00', '2025-06-06 19:00:00', '2025-06-07 00:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (21, '2024-02-22 23:00:00', '2024-02-22 23:00:00', '2024-02-23 00:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (22, '2025-08-24 20:00:00', '2025-08-24 20:00:00', '2025-08-25 00:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (23, '2025-03-01 01:00:00', '2025-03-01 01:00:00', '2025-03-01 05:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (24, '2025-07-26 06:00:00', '2025-07-26 06:00:00', '2025-07-26 14:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (25, '2025-04-23 13:00:00', '2025-04-23 13:00:00', '2025-04-23 20:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (26, '2025-11-01 15:00:00', '2025-11-01 15:00:00', '2025-11-02 00:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (27, '2024-06-16 18:00:00', '2024-06-16 18:00:00', '2024-06-16 21:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (28, '2024-02-02 23:00:00', '2024-02-02 23:00:00', '2024-02-03 04:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (29, '2024-04-09 16:00:00', '2024-04-09 16:00:00', '2024-04-09 19:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (30, '2024-08-25 17:00:00', '2024-08-25 17:00:00', '2024-08-25 19:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (31, '2024-11-10 21:00:00', '2024-11-10 21:00:00', '2024-11-11 02:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (32, '2025-02-27 19:00:00', '2025-02-27 19:00:00', '2025-02-28 00:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (33, '2025-02-25 08:00:00', '2025-02-25 08:00:00', '2025-02-25 14:00:00', 'AC009', 'Orlando International', 'London Heathrow'),
 (34, '2024-02-08 14:00:00', '2024-02-08 14:00:00', '2024-02-08 23:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (35, '2025-11-11 22:00:00', '2025-11-11 22:00:00', '2025-11-12 08:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (36, '2025-08-25 00:00:00', '2025-08-25 00:00:00', '2025-08-25 01:00:00', 'AC005', 'JFK International', 'Singapore Changi'),
 (37, '2025-07-18 00:00:00', '2025-07-18 00:00:00', '2025-07-18 06:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (38, '2025-05-20 21:00:00', '2025-05-20 21:00:00', '2025-05-21 02:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (39, '2025-11-03 12:00:00', '2025-11-03 12:00:00', '2025-11-03 18:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (40, '2024-03-24 02:00:00', '2024-03-24 02:00:00', '2024-03-24 06:00:00', 'AC004', 'Dallas/Fort Worth International', 'Toronto Pearson'),
 (41, '2025-09-21 14:00:00', '2025-09-21 14:00:00', '2025-09-21 15:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (42, '2024-12-07 11:00:00', '2024-12-07 11:00:00', '2024-12-07 12:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (43, '2025-11-11 18:00:00', '2025-11-11 18:00:00', '2025-11-11 20:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (44, '2024-06-25 05:00:00', '2024-06-25 05:00:00', '2024-06-25 12:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (45, '2024-08-22 13:00:00', '2024-08-22 13:00:00', '2024-08-22 17:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (46, '2024-06-02 09:00:00', '2024-06-02 09:00:00', '2024-06-02 19:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (47, '2024-06-18 17:00:00', '2024-06-18 17:00:00', '2024-06-19 02:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (48, '2025-10-25 21:00:00', '2025-10-25 21:00:00', '2025-10-25 23:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (49, '2025-01-04 11:00:00', '2025-01-04 11:00:00', '2025-01-04 13:00:00', 'AC009', 'JFK International', 'Sydney Kingsford Smith'),
 (50, '2025-06-20 02:00:00', '2025-06-20 02:00:00', '2025-06-20 03:00:00', 'AC009', 'JFK International', 'Sydney Kingsford Smith'),
 (51, '2025-03-03 06:00:00', '2025-03-03 06:00:00', '2025-03-03 14:00:00', 'AC001', 'JFK International', 'Singapore Changi'),
 (52, '2025-03-04 18:00:00', '2025-03-04 18:00:00', '2025-03-04 19:00:00', 'AC010', 'JFK International', 'Singapore Changi'),
 (53, '2025-02-19 13:00:00', '2025-02-19 13:00:00', '2025-02-19 22:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (54, '2024-06-18 23:00:00', '2024-06-18 23:00:00', '2024-06-19 08:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (55, '2024-07-18 10:00:00', '2024-07-18 10:00:00', '2024-07-18 11:00:00', 'AC008', 'Dallas/Fort Worth International', 'Toronto Pearson'),
 (56, '2025-07-16 20:00:00', '2025-07-16 20:00:00', '2025-07-16 21:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (57, '2024-06-19 08:00:00', '2024-06-19 08:00:00', '2024-06-19 18:00:00', 'AC008', 'Orlando International', 'Paris Charles de Gaulle'),
 (58, '2025-01-02 15:00:00', '2025-01-02 15:00:00', '2025-01-02 20:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (59, '2024-08-15 08:00:00', '2024-08-15 08:00:00', '2024-08-15 17:00:00', 'AC005', 'Orlando International', 'Paris Charles de Gaulle'),
 (60, '2025-01-01 16:00:00', '2025-01-01 16:00:00', '2025-01-01 20:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (61, '2024-04-19 04:00:00', '2024-04-19 04:00:00', '2024-04-19 07:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (62, '2024-06-12 04:00:00', '2024-06-12 04:00:00', '2024-06-12 12:00:00', 'AC010', 'Denver International', 'Dubai International'),
 (63, '2024-11-03 05:00:00', '2024-11-03 05:00:00', '2024-11-03 07:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (64, '2025-11-01 01:00:00', '2025-11-01 01:00:00', '2025-11-01 05:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (65, '2024-07-04 10:00:00', '2024-07-04 10:00:00', '2024-07-04 20:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (66, '2025-06-10 17:00:00', '2025-06-10 17:00:00', '2025-06-10 19:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (67, '2025-01-24 08:00:00', '2025-01-24 08:00:00', '2025-01-24 18:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (68, '2024-08-13 21:00:00', '2024-08-13 21:00:00', '2024-08-14 05:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (69, '2024-08-07 14:00:00', '2024-08-07 14:00:00', '2024-08-08 00:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (70, '2025-06-18 06:00:00', '2025-06-18 06:00:00', '2025-06-18 14:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (71, '2024-07-07 06:00:00', '2024-07-07 06:00:00', '2024-07-07 07:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (72, '2025-10-06 16:00:00', '2025-10-06 16:00:00', '2025-10-07 02:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (73, '2025-11-21 14:00:00', '2025-11-21 14:00:00', '2025-11-21 18:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (74, '2024-01-25 05:00:00', '2024-01-25 05:00:00', '2024-01-25 08:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (75, '2024-10-05 11:00:00', '2024-10-05 11:00:00', '2024-10-05 18:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (76, '2024-04-02 16:00:00', '2024-04-02 16:00:00', '2024-04-02 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (77, '2025-10-21 15:00:00', '2025-10-21 15:00:00', '2025-10-21 17:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (78, '2024-03-08 23:00:00', '2024-03-08 23:00:00', '2024-03-09 09:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (79, '2025-10-19 01:00:00', '2025-10-19 01:00:00', '2025-10-19 05:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (80, '2025-07-23 22:00:00', '2025-07-23 22:00:00', '2025-07-24 05:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (81, '2025-09-11 09:00:00', '2025-09-11 09:00:00', '2025-09-11 17:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (82, '2024-11-27 18:00:00', '2024-11-27 18:00:00', '2024-11-27 21:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (83, '2024-05-17 02:00:00', '2024-05-17 02:00:00', '2024-05-17 04:00:00', 'AC006', 'Orlando International', 'London Heathrow'),
 (84, '2025-12-04 21:00:00', '2025-12-04 21:00:00', '2025-12-05 02:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (85, '2025-04-12 21:00:00', '2025-04-12 21:00:00', '2025-04-13 03:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (86, '2024-12-18 22:00:00', '2024-12-18 22:00:00', '2024-12-19 00:00:00', 'AC005', 'JFK International', 'Singapore Changi'),
 (87, '2024-03-14 05:00:00', '2024-03-14 05:00:00', '2024-03-14 15:00:00', 'AC004', 'JFK International', 'Frankfurt Airport'),
 (88, '2024-12-27 06:00:00', '2024-12-27 06:00:00', '2024-12-27 15:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (89, '2025-06-09 09:00:00', '2025-06-09 09:00:00', '2025-06-09 17:00:00', 'AC009', 'JFK International', 'Frankfurt Airport'),
 (90, '2025-06-21 04:00:00', '2025-06-21 04:00:00', '2025-06-21 05:00:00', 'AC009', 'Dallas/Fort Worth International', 'Toronto Pearson'),
 (91, '2025-08-01 15:00:00', '2025-08-01 15:00:00', '2025-08-02 01:00:00', 'AC003', 'JFK International', 'Frankfurt Airport'),
 (92, '2024-08-22 09:00:00', '2024-08-22 09:00:00', '2024-08-22 19:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (93, '2024-05-11 19:00:00', '2024-05-11 19:00:00', '2024-05-12 01:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (94, '2025-01-25 05:00:00', '2025-01-25 05:00:00', '2025-01-25 06:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (95, '2024-02-27 00:00:00', '2024-02-27 00:00:00', '2024-02-27 01:00:00', 'AC005', 'JFK International', 'Frankfurt Airport'),
 (96, '2024-01-22 18:00:00', '2024-01-22 18:00:00', '2024-01-23 00:00:00', 'AC010', 'JFK International', 'Frankfurt Airport'),
 (97, '2025-05-27 01:00:00', '2025-05-27 01:00:00', '2025-05-27 08:00:00', 'AC002', 'JFK International', 'Frankfurt Airport'),
 (98, '2025-07-06 01:00:00', '2025-07-06 01:00:00', '2025-07-06 05:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (99, '2025-07-14 15:00:00', '2025-07-14 15:00:00', '2025-07-14 17:00:00', 'AC005', 'JFK International', 'Sydney Kingsford Smith'),
 (100, '2024-08-13 11:00:00', '2024-08-13 11:00:00', '2024-08-13 21:00:00', 'AC001', 'JFK International', 'Sydney Kingsford Smith'),
 (101, '2025-04-15 18:00:00', '2025-04-15 18:00:00', '2025-04-15 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (102, '2025-05-08 18:00:00', '2025-05-08 18:00:00', '2025-05-08 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (103, '2025-07-10 18:00:00', '2025-07-10 18:00:00', '2025-07-10 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (104, '2025-08-12 18:00:00', '2025-08-12 18:00:00', '2025-08-12 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (105, '2025-09-14 18:00:00', '2025-09-14 18:00:00', '2025-09-14 23:00:00', 'AC008', 'Dallas/Fort Worth International', 'Toronto Pearson'),
 (106, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (107, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (108, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (109, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC007', 'JFK International', 'Sydney Kingsford Smith'),
 (110, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (111, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (112, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (113, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (114, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC008', 'Orlando International', 'London Heathrow'),
 (115, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC008', 'Orlando International', 'London Heathrow'),
 (116, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC001', 'JFK International', 'Singapore Changi'),
 (117, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC001', 'JFK International', 'Singapore Changi'),
 (118, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC001', 'Orlando International', 'London Heathrow'),
 (119, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (120, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (121, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (122, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC001', 'JFK International', 'Singapore Changi'),
 (123, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (124, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (125, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC008', 'Orlando International', 'Paris Charles de Gaulle'),
 (126, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC008', 'Denver International', 'Dubai International'),
 (127, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (128, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (129, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (130, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (131, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (132, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (133, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC001', 'Orlando International', 'London Heathrow'),
 (134, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (135, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (136, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (137, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (138, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (139, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (140, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (141, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (142, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (143, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (144, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (145, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (146, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (147, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (148, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (149, '2024-12-04 18:00:00', '2024-12-04 18:00:00', '2024-12-04 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (150, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC007', 'JFK International', 'Frankfurt Airport'),
 (151, '2024-12-05 18:00:00', '2024-12-05 18:00:00', '2024-12-05 23:00:00', 'AC008', 'JFK International', 'Frankfurt Airport'),
 (152, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC001', 'JFK International', 'Frankfurt Airport'),
 (153, '2024-12-07 18:00:00', '2024-12-07 18:00:00', '2024-12-07 23:00:00', 'AC006', 'Dallas/Fort Worth International', 'Toronto Pearson'),
 (154, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC006', 'JFK International', 'Frankfurt Airport'),
 (155, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC006', 'JFK International', 'Sydney Kingsford Smith'),

In [14]:
%%sql
select * from transactions;

 * sqlite:///airlines.db
Done.

[(1, '2024-11-01 00:00:00', '2024-05-21 00:00:00', 28, 28, 1, 60, 33, 29),
 (2, '2024-11-19 00:00:00', '2024-07-08 00:00:00', 17, 28, 1, 3, 29, 28),
 (3, '2024-04-14 00:00:00', '2024-03-19 00:00:00', 94, 27, 0, 77, 45, 16),
 (4, '2024-03-15 00:00:00', '2024-04-26 00:00:00', 23, 26, 1, 1, 11, 36),
 (5, '2024-11-05 00:00:00', '2024-11-10 00:00:00', 46, 19, 1, 93, 8, 29),
 (6, '2024-08-06 00:00:00', '2024-02-05 00:00:00', 57, 10, 1, 65, 8, 50),
 (7, '2024-03-19 00:00:00', '2024-06-15 00:00:00', 5, 9, 1, 73, 39, 33),
 (8, '2024-01-03 00:00:00', '2024-08-18 00:00:00', 83, 38, 1, 79, 43, 38),
 (9, '2024-09-20 00:00:00', '2024-06-09 00:00:00', 16, 39, 1, 9, 19, 19),
 (10, '2024-04-23 00:00:00', '2024-10-19 00:00:00', 78, 36, 1, 38, 44, 48),
 (11, '2024-11-03 00:00:00', '2024-07-06 00:00:00', 11, 11, 1, 7, 4, 36),
 (12, '2024-02-22 00:00:00', '2024-06-07 00:00:00', 83, 29, 1, 1, 25, 36),
 (13, '2024-04-30 00:00:00', '2024-02-14 00:00:00', 86, 10, 0, 56, 40, 32),
 (14, '2024-05-10 00:00:00', '2024-06-06 00:00:00', 74, 37, 1, 19, 32, 8),
 (15, '2024-07-03 00:00:00', '2024-06-05 00:00:00', 70, 38, 1, 44, 46, 46),
 (16, '2024-05-17 00:00:00', '2024-12-02 00:00:00', 28, 1, 1, 25, 17, 35),
 (17, '2024-10-12 00:00:00', '2024-08-05 00:00:00', 38, 49, 1, 71, 10, 47),
 (18, '2024-11-28 00:00:00', '2024-02-18 00:00:00', 93, 18, 1, 11, 34, 42),
 (19, '2024-02-10 00:00:00', '2024-12-14 00:00:00', 94, 22, 1, 35, 7, 44),
 (20, '2024-05-05 00:00:00', '2024-09-13 00:00:00', 82, 1, 0, 87, 1, 48),
 (21, '2024-10-09 00:00:00', '2024-10-09 00:00:00', 25, 35, 0, 100, 24, 32),
 (22, '2024-06-17 00:00:00', '2024-05-13 00:00:00', 63, 42, 0, 70, 31, 15),
 (23, '2024-03-09 00:00:00', '2024-12-01 00:00:00', 63, 7, 0, 16, 31, 12),
 (24, '2024-10-12 00:00:00', '2024-07-07 00:00:00', 17, 38, 0, 23, 19, 50),
 (25, '2024-02-22 00:00:00', '2024-03-11 00:00:00', 61, 46, 1, 19, 4, 7),
 (26, '2024-06-23 00:00:00', '2024-06-06 00:00:00', 21, 40, 1, 74, 41, 8),
 (27, '2024-04-22 00:00:00', '2024-12-19 00:00:00', 40, 24, 0, 60, 39, 15),
 (28, '2024-04-05 00:00:00', '2024-01-10 00:00:00', 59, 46, 1, 47, 2, 36),
 (29, '2024-05-11 00:00:00', '2024-12-20 00:00:00', 43, 6, 1, 98, 49, 26),
 (30, '2024-09-23 00:00:00', '2024-11-10 00:00:00', 3, 42, 1, 46, 16, 36),
 (31, '2024-12-23 00:00:00', '2024-12-09 00:00:00', 4, 18, 1, 17, 28, 38),
 (32, '2024-06-04 00:00:00', '2024-05-19 00:00:00', 69, 26, 0, 88, 41, 39),
 (33, '2024-09-10 00:00:00', '2024-10-03 00:00:00', 74, 17, 0, 72, 20, 13),
 (34, '2024-02-06 00:00:00', '2024-04-10 00:00:00', 97, 7, 0, 68, 46, 35),
 (35, '2024-07-18 00:00:00', '2024-06-14 00:00:00', 6, 36, 0, 96, 7, 34),
 (36, '2024-04-21 00:00:00', '2024-11-11 00:00:00', 52, 7, 0, 79, 20, 32),
 (37, '2024-07-30 00:00:00', '2024-11-11 00:00:00', 38, 1, 0, 80, 38, 19),
 (38, '2024-03-30 00:00:00', '2024-06-16 00:00:00', 23, 15, 0, 6, 36, 27),
 (39, '2024-11-12 00:00:00', '2024-12-30 00:00:00', 80, 14, 1, 36, 21, 1),
 (40, '2024-03-28 00:00:00', '2024-01-30 00:00:00', 44, 27, 1, 18, 43, 2),
 (41, '2024-07-14 00:00:00', '2024-06-13 00:00:00', 39, 5, 1, 89, 42, 28),
 (42, '2024-06-05 00:00:00', '2024-10-04 00:00:00', 97, 20, 0, 15, 26, 17),
 (43, '2024-09-27 00:00:00', '2024-07-18 00:00:00', 4, 49, 1, 55, 38, 38),
 (44, '2024-02-20 00:00:00', '2024-05-26 00:00:00', 92, 44, 0, 7, 2, 5),
 (45, '2024-03-21 00:00:00', '2024-12-16 00:00:00', 79, 31, 0, 21, 14, 33),
 (46, '2024-01-08 00:00:00', '2024-12-04 00:00:00', 10, 30, 1, 78, 24, 43),
 (47, '2024-01-10 00:00:00', '2024-01-02 00:00:00', 69, 30, 1, 10, 35, 38),
 (48, '2024-06-30 00:00:00', '2024-03-23 00:00:00', 8, 34, 0, 34, 48, 41),
 (49, '2024-01-23 00:00:00', '2024-01-05 00:00:00', 44, 47, 1, 100, 7, 36),
 (50, '2024-10-03 00:00:00', '2024-08-07 00:00:00', 60, 25, 1, 25, 35, 35),
 (51, '2024-12-20 00:00:00', '2024-01-21 00:00:00', 16, 3, 0, 17, 12, 48),
 (52, '2024-01-25 00:00:00', '2024-12-23 00:00:00', 96, 27, 0, 86, 22, 23),
 (53, '2024-02-09 00:00:00', '2024-04-22 00:00:00', 15, 42, 0, 37, 25, 4),
 (54, '2024-02-08 00:00:00', '2024-09-09 00:00:00', 99, 30, 0, 45, 9, 17),
 (55, '2024-04-15 00:00:00', '2024-10-10 00:00:00', 19, 10, 0, 4, 48, 44),
 (56, '2024-02-10 00:00:00', '2024-05-29 00:00:00', 74, 43, 1, 26, 18, 28),
 (57, '2024-10-29 00:00:00', '2024-11-18 00:00:00', 54, 35, 0, 2, 20, 31),
 (58, '2024-06-11 00:00:00', '2024-09-18 00:00:00', 60, 21, 1, 68, 10, 3),
 (59, '2024-12-03 00:00:00', '2024-08-20 00:00:00', 12, 4, 0, 58, 7, 20),
 (60, '2024-01-30 00:00:00', '2024-10-21 00:00:00', 45, 30, 1, 38, 2, 33),
 (61, '2024-01-09 00:00:00', '2024-06-15 00:00:00', 29, 22, 1, 87, 45, 19),
 (62, '2024-08-11 00:00:00', '2024-09-14 00:00:00', 34, 44, 1, 98, 28, 16),
 (63, '2024-02-07 00:00:00', '2024-08-28 00:00:00', 98, 17, 1, 81, 9, 41),
 (64, '2024-09-13 00:00:00', '2024-02-21 00:00:00', 24, 17, 0, 71, 36, 45),
 (65, '2024-05-29 00:00:00', '2024-10-29 00:00:00', 69, 9, 0, 93, 47, 18),
 (66, '2024-08-31 00:00:00', '2024-12-06 00:00:00', 85, 36, 1, 39, 29, 29),
 (67, '2024-05-24 00:00:00', '2024-11-29 00:00:00', 84, 42, 1, 12, 10, 38),
 (68, '2024-04-21 00:00:00', '2024-07-27 00:00:00', 57, 32, 1, 40, 33, 30),
 (69, '2024-12-29 00:00:00', '2024-02-21 00:00:00', 21, 46, 0, 51, 45, 40),
 (70, '2024-03-23 00:00:00', '2024-01-14 00:00:00', 65, 21, 0, 91, 21, 2),
 (71, '2024-01-17 00:00:00', '2024-04-10 00:00:00', 52, 32, 0, 10, 45, 9),
 (72, '2024-05-20 00:00:00', '2024-07-21 00:00:00', 37, 6, 0, 50, 30, 36),
 (73, '2024-05-15 00:00:00', '2024-05-28 00:00:00', 94, 4, 0, 48, 9, 13),
 (74, '2024-01-01 00:00:00', '2024-12-18 00:00:00', 90, 12, 0, 73, 36, 30),
 (75, '2024-04-11 00:00:00', '2024-04-20 00:00:00', 21, 13, 0, 78, 35, 25),
 (76, '2024-11-06 00:00:00', '2024-02-24 00:00:00', 91, 16, 1, 53, 49, 15),
 (77, '2024-12-24 00:00:00', '2024-05-22 00:00:00', 53, 6, 0, 77, 40, 18),
 (78, '2024-12-26 00:00:00', '2024-03-26 00:00:00', 45, 5, 1, 63, 38, 14),
 (79, '2024-07-11 00:00:00', '2024-04-22 00:00:00', 21, 32, 1, 34, 45, 35),
 (80, '2024-02-21 00:00:00', '2024-12-18 00:00:00', 56, 38, 0, 94, 18, 12),
 (81, '2024-04-26 00:00:00', '2024-08-16 00:00:00', 56, 3, 1, 22, 22, 22),
 (82, '2024-06-25 00:00:00', '2024-03-31 00:00:00', 34, 35, 0, 72, 49, 43),
 (83, '2024-02-11 00:00:00', '2024-12-29 00:00:00', 90, 1, 1, 37, 20, 32),
 (84, '2024-06-18 00:00:00', '2024-11-12 00:00:00', 30, 20, 1, 83, 37, 16),
 (85, '2024-03-20 00:00:00', '2024-01-06 00:00:00', 74, 5, 0, 39, 3, 29),
 (86, '2024-02-28 00:00:00', '2024-03-17 00:00:00', 1, 33, 0, 80, 32, 31),
 (87, '2024-02-18 00:00:00', '2024-10-29 00:00:00', 11, 29, 0, 3, 35, 47),
 (88, '2024-05-10 00:00:00', '2024-07-30 00:00:00', 81, 37, 1, 13, 32, 22),
 (89, '2024-07-20 00:00:00', '2024-07-28 00:00:00', 93, 10, 1, 93, 14, 8),
 (90, '2024-06-22 00:00:00', '2024-09-13 00:00:00', 29, 28, 0, 19, 33, 39),
 (91, '2024-01-28 00:00:00', '2024-04-10 00:00:00', 64, 45, 1, 87, 16, 49),
 (92, '2024-06-09 00:00:00', '2024-03-10 00:00:00', 2, 35, 0, 55, 27, 21),
 (93, '2024-07-24 00:00:00', '2024-12-28 00:00:00', 57, 20, 0, 2, 22, 5),
 (94, '2024-05-15 00:00:00', '2024-05-14 00:00:00', 21, 14, 0, 53, 34, 28),
 (95, '2024-06-06 00:00:00', '2024-09-22 00:00:00', 43, 2, 1, 93, 23, 28),
 (96, '2024-12-28 00:00:00', '2024-03-30 00:00:00', 100, 25, 0, 16, 48, 7),
 (97, '2024-09-26 00:00:00', '2024-07-19 00:00:00', 36, 34, 0, 80, 42, 34),
 (98, '2024-02-13 00:00:00', '2024-08-01 00:00:00', 47, 33, 1, 96, 20, 19),
 (99, '2024-04-24 00:00:00', '2024-03-03 00:00:00', 42, 23, 1, 45, 24, 22),
 (100, '2024-05-29 00:00:00', '2024-02-21 00:00:00', 88, 4, 0, 49, 33, 13)]

In [61]:
%%sql
select * from passengers where Nationality ='United States' and Age >50;

 * sqlite:///airlines.db
Done.

[(103, 'Peter Jones', '380 Broadway', 79, 'United States', 4),
 (115, 'Brian Johnson', '443 Broadway', 56, 'United States', 16),
 (120, 'Susan White', '957 Pine St', 58, 'United States', 21)]

In [58]:
%%sql 
select * from logs where data like '%2024-01-01%';

 * sqlite:///airlines.db
Done.

[]

In [ ]:
%%sql
SELECT FlID,FlightDate,Departure,Arrival,Aircraft, Airport, Destination 
    FROM Flight_Schedule f inner join AirFare a on f.NetFare=a.AfID inner join Route r on a.Route=r.RtID 
        where FlightDate = '2024-12-07 11:00:00' and Airport like '%JFK%'

 * sqlite:///airlines.db
Done.

[(42, '2024-12-07 11:00:00', '2024-12-07 11:00:00', '2024-12-07 12:00:00', 'AC007', 'JFK International', 'Frankfurt Airport')]

In [27]:
%%sql
SELECT FlID,FlightDate,Departure,Arrival,Aircraft, 
Airport, Destination FROM Flight_Schedule f inner join AirFare a on f.NetFare=a.AfID inner join Route r on a.Route=r.RtID where Aircraft ='AC007' and Destination like '%Singapore%'

 * sqlite:///airlines.db
Done.

[(2, '2025-07-06 08:00:00', '2025-07-06 08:00:00', '2025-07-06 17:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (124, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (138, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC007', 'JFK International', 'Singapore Changi')]

In [28]:
%%sql
SELECT FlID,FlightDate,Departure,Arrival,Aircraft, 
Airport, Destination FROM Flight_Schedule f inner join AirFare a on f.NetFare=a.AfID inner join Route r on a.Route=r.RtID where Aircraft ='AC007' and Destination like '%Singapore%'

 * sqlite:///airlines.db
Done.

[(2, '2025-07-06 08:00:00', '2025-07-06 08:00:00', '2025-07-06 17:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (124, '2024-12-08 18:00:00', '2024-12-08 18:00:00', '2024-12-08 23:00:00', 'AC007', 'JFK International', 'Singapore Changi'),
 (138, '2024-12-06 18:00:00', '2024-12-06 18:00:00', '2024-12-06 23:00:00', 'AC007', 'JFK International', 'Singapore Changi')]

In [35]:
%%sql
SELECT rt.Airport, rt.Destination, COUNT(t.Passenger) AS TotalPassengers
FROM Route rt
JOIN Flight_Schedule fs ON rt.RtID = fs.FlID
JOIN Transactions t ON fs.FlID = t.Flight
GROUP BY rt.Airport, rt.Destination
ORDER BY TotalPassengers DESC LIMIT 5;

 * sqlite:///airlines.db
Done.

[('Miami International', 'Paris Charles de Gaulle', 10),
 ('Orlando International', 'Paris Charles de Gaulle', 7),
 ('Orlando International', 'Hong Kong International', 6),
 ('Seattle-Tacoma International', 'Sydney Kingsford Smith', 6),
 ('Dallas/Fort Worth International', 'Toronto Pearson', 5)]

# total revenue

In [38]:
%%sql

SELECT rt.Airport, rt.Destination, 
       SUM(t.Charges + af.Fare - d.Amount) AS TotalRevenue
FROM Transactions t
JOIN Flight_Schedule fs ON t.Flight = fs.FlID
JOIN Route rt ON fs.FlID = rt.RtID
JOIN AirFare af ON rt.RtID = af.Route
JOIN Discounts d ON t.Discount = d.DiID
GROUP BY rt.Airport, rt.Destination
ORDER BY TotalRevenue ;

 * sqlite:///airlines.db
Done.

[('Denver International', 'Dubai International', 952.1299999999999),
 ('Miami International', 'Paris Charles de Gaulle', 1705.5500000000002),
 ('JFK International', 'Singapore Changi', 1807.9),
 ('Orlando International', 'London Heathrow', 2028.7600000000002),
 ('Dallas/Fort Worth International', 'Toronto Pearson', 3238.26),
 ('Orlando International', 'Paris Charles de Gaulle', 3552.4300000000003),
 ('JFK International', 'Frankfurt Airport', 86087.72)]

Employees in High-Traffic States
employees_in_states_query = """

# most loyal passenger

In [43]:
%%sql 
SELECT p.Name, COUNT(t.TsID) AS BookingsCount
FROM Passengers p
JOIN Transactions t ON p.PsID = t.Passenger
GROUP BY p.Name
ORDER BY BookingsCount DESC
LIMIT 5;

 * sqlite:///airlines.db
Done.

[('Robert Moore', 1)]

In [44]:
# triggers

In [ ]:
%%sql 
CREATE TRIGGER InsertScheduleLog
AFTER INSERT ON Flight_Schedule
FOR EACH ROW
BEGIN
    INSERT INTO LOGS (OPERATION, DATA)
    VALUES (
        'INSERT',
          'Flight_Schedule: ' || NEW.FlID || ', ' || NEW.FlightDate || ', ' || NEW.Departure || ', ' || 
        NEW.Arrival || ', ' || NEW.Aircraft || ', ' || NEW.NetFare
        );
END;

SyntaxError: invalid syntax (679939352.py, line 1)

In [ ]:
%%sql 
CREATE TRIGGER updatePassengerLog
AFTER UPDATE ON Passengers
FOR EACH ROW
BEGIN
    INSERT INTO LOGS (OPERATION, DATA)
    VALUES (
        'UPDATE',
        'Passengers: ' || 'Old PsID: ' || OLD.PsID || ', New PsID: ' || NEW.PsID || ', ' ||
        'Old Name: ' || OLD.Name || ', New Name: ' || NEW.Name || ', ' ||
        'Old Address: ' || OLD.Address || ', New Address: ' || NEW.Address || ', ' ||
        'Old Age: ' || OLD.Age || ', New Age: ' || NEW.Age || ', ' ||
        'Old Nationality: ' || OLD.Nationality || ', New Nationality: ' || NEW.Nationality || ', ' ||
        'Old Contacts: ' || OLD.Contacts || ', New Contacts: ' || NEW.Contacts
    );
END;

SyntaxError: invalid syntax (267083208.py, line 1)

In [ ]:
%%sql
CREATE TRIGGER IF NOT EXISTS deletePassengerLog
AFTER DELETE ON Passengers
FOR EACH ROW
BEGIN
    INSERT INTO LOGS (OPERATION, DATA)
    VALUES (
        'DELETE',
        'Passengers: ' || OLD.PsID || ', Name: ' || OLD.Name || ', Address: ' || OLD.Address || ', ' ||
        'Age: ' || OLD.Age || ', Nationality: ' || OLD.Nationality || ', Contacts: ' || OLD.Contacts
    );
END;

In [ ]:
%%sql 
CREATE TRIGGER IF NOT EXISTS updateTransactionLog
AFTER UPDATE ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO LOGS (OPERATION, DATA)
    VALUES (
        'UPDATE',
        'Booking: ' || 'Old: ' || OLD.TsID || ', ' || OLD.BookingDate || ', ' || OLD.DepartureDate || ', ' || 
        OLD.Passenger || ', ' || OLD.Flight || ', ' || OLD.Type || ', ' || 
        OLD.Employee || ', ' || OLD.Charges || ', ' || OLD.Discount || ' | ' ||
        'New: ' || NEW.TsID || ', ' || NEW.BookingDate || ', ' || NEW.DepartureDate || ', ' || 
        NEW.Passenger || ', ' || NEW.Flight || ', ' || NEW.Type || ', ' || 
        NEW.Employee || ', ' || NEW.Charges || ', ' || NEW.Discount
    );
END;

SyntaxError: invalid syntax (1972461751.py, line 1)

In [48]:
%%sql
SELECT p.Nationality, AVG(d.Amount) AS AvgDiscount
FROM Passengers p
JOIN Transactions t ON p.PsID = t.Passenger
JOIN Discounts d ON t.Discount = d.DiID
GROUP BY p.Nationality;

 * sqlite:///airlines.db
Done.

[('United States', 25.0)]

In [56]:
%%sql
SELECT br.State as StateID, COUNT(fs.FlID) AS FlightsCount
FROM Branches br
JOIN Flight_Schedule fs ON br.BrID = fs.FlID 
GROUP BY br.State
ORDER BY FlightsCount DESC
LIMIT 3;

 * sqlite:///airlines.db
Done.

[(9, 2), (2, 2), (17, 1)]